### ISSUE TITLE
How to add/edit bookings and/or user roles?

### ISSUE THREAD

**Issue by SomeDevWeb** [patrickrobrecht/flexible-event-and-booking-manager#21]
Hello.

First of all, a big **CONGRATS and thanks for this project**. It's the first one after a few tens I searched that actually works with the F**ING PHP 8.2 and uses Laravel 10! And on top of all I could actually install it following the instructions :)
This seems to be quite rare in the git laravel projects from as far as I saw where everything is made for ancient laravels or only up to PHP 7.x.... So ya, well done for that!!!

Now, couple of questions please:
1. I would need a project for a charity but for room booking where the visitors can see a table with the days booked/available per each room. I presume this project still would work well by replacing Events with Rooms, as the principle would be the same...
2. I don't understand how you add admin users and the events. I see the mysql tables are created fine in the DB, but is there a GUI section for user roles management or is it done in the DB?

Anyway, as a thought, I'm very new to Laravel, but I want to learn ASAP and I'll have a look at this code and come back with updates.
Thanks again!

**Comment by patrickrobrecht** [comment]
1.) Room management is not included and not planned from my side. But feel free to add your own extensions in a fork of this repository.

2.) The application includes management of users and user roles.

To create some default user roles run `php artisan db:seed --class=UserRoleSeeder`. It creates the user roles defined in `database/seeders/UserRoleSeeder.php`.

If self-registration is enabled, you can create your first user via registration and assign a role via the database:
```INSERT INTO `user_user_role` (`user_id`, `user_role_id`, `created_at`, `updated_at`) VALUES (1, 1, NOW(), NOW());```

After that you can login with your Administrator account and manage everything via the web interface (including additional users, user roles, events, booking options, bookings, event series, locations, organizations). Just the UI for custom booking forms with additional fields is still missing, here just directly editing via phpMyAdmin or HeidiSQL is possible.
